
GenerateLog = function(name){
  #' GenerateLog
  #' @description This function generates the log file that would store all the events generated by the code.
  #' @param name the name of the log file
  #' @return True if the log file is generated

  out <- tryCatch(
    {
      ### ------ Create file ------ ###
      zz <- file(paste0('log/',name), open = "wt")

      sink(file=zz,split = TRUE,append = TRUE,type = "output")
      sink(file=zz,split = FALSE,append = TRUE,type = "message")
      message('\n -----------------------------------')
      ### -------- Storage system info ------ ####
      cat(paste0('\n Working Directory: ', getwd()))
      cat(paste0('\n User Name: ', Sys.info()[["user"]]))
      cat(R.Version()$version.string)
      cat(paste0('\n Operating System: ',   Sys.info()[['version']]))
      cat(paste0('\n Machine: ',   Sys.info()[['nodename']]))
      cat(paste0('\n Log Start Time: ',   format(Sys.time(), "%a %b %d %X %Y")))
      message('\n -----------------------------------')
      return(T)

    },
    error=function(cond) {
      message("please check your overwriting permissions.")
      message(cond)
      stop()
      return(NA)
    }
  )

  return(out)

}

SummaryConcordances = function(concordances_POA,concordances_SA3){
  #' SummaryConcordances
  #' @description Create a summary of the concordances involved in the data linkage.
  #' @param concordances_POA concordances using in the POA linkage
  #' @param concordances_SA3 concordances using in the SA3 linkage
  #' @return a data frame with the concordances involved in the data linkage.

  ####### ------- Create a concordances summary table -------- #########
  #### ------ concordances POA ------- ######
  concordances_POA = as.data.frame(apply(concordances_POA[,-c(1)],2,function(x){unique(x)}))
  #### ------ concordances SA3 ------- ######
  concordances_SA3 = as.data.frame(apply(concordances_SA3[,-c(1)],2,function(x){names(head(table(x),2))}))
  concordances_SA3[1,] = concordances_SA3[2,]
  concordances_SA3[2,] = 0
  #### ---- Join and clean ---- #####
  concordances_output= as.data.frame(cbind(concordances_POA,concordances_SA3))[1,]
  concordances_output = as.data.frame(t(rbind(concordances_output,colnames(concordances_output))))
  rownames(concordances_output) = NULL
  colnames(concordances_output) = c('concordances','year')
  #### ---- Extract information ---- #####
  concordances_output$year = gsub(pattern = 'X',replacement = "", concordances_output$year)
  concordances_output$wave = as.numeric(lapply(concordances_output$year, function(x){strsplit(x,'_')[[1]][[2]]}))
  concordances_output$potential_ABS = as.numeric(lapply(concordances_output$year, function(x){strsplit(x,'_')[[1]][[1]]}))
  concordances_output$origin = as.character(lapply(concordances_output$concordances, function(x){strsplit(x,'_')[[1]][[1]]}))
  concordances_output$destination = as.character(lapply(concordances_output$concordances, function(x){strsplit(x,'_')[[1]][[1]]}))
  concordances_output$year_destination =as.character(lapply(concordances_output$concordances, function(x){strsplit(x,'_')[[1]][[4]]}))
  concordances_output$source = paste0("ASGS Geographic Correspondences (",concordances_output$year_destination,")")
  #### ------ Organise table ------ #####
  concordances_output = concordances_output[,c('wave','potential_ABS','origin','destination','year_destination','source')]
  colnames(concordances_output) = c('Wave','Potential ABS','Origin','Destination','Year destination','Source')
  return(concordances_output)
}


##### ----- Create a table with information ------- #####
SummaryMetrics = function(metrics_POA,metrics_SA3){
  #' SummaryMetrics
  #' @description Create a summary with important information about the data linkage, such as year, cohort,
  #' linkage, missing values, not linked areas, not linked individuals and the quality of the data linkage.
  #' @param metrics_POA Metrics created in the POA linkage.
  #' @param metrics_SA3 Metrics created in the SA3 linkage.
  #' @return a data frame with all the information mentioned before.
  metrics_POA$Linkage = "POA to SA3"
  metrics_SA3$Linkage = "SA3 to SA3"
  Metrics_consolidate = rbind(metrics_POA,metrics_SA3)
  Metrics_consolidate$year = as.numeric(as.numeric(lapply(Metrics_consolidate$year, function(x){strsplit(x,'_')[[1]][[2]]})))
  Metrics_consolidate = Metrics_consolidate[,c('year','N','Linkage','MissingValues','NotLinkedAreas','NotLinkedIndividuals','Good','Acceptable','Poor')]
  colnames(Metrics_consolidate) = c( 'Cohort','N' ,'Linkage','Sample attrition', 'Not Linked Areas', 'Not Linked Individuals', 'Good','Acceptable','Poor')
  return(Metrics_consolidate)
}


